# Generated by Django 3.2.5 on 2021-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('Employment_type', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('work_location', models.CharField(max_length=50)),
            ],
        ),
    ]
