# Generated by Django 3.2.5 on 2021-10-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='work_location',
        ),
    ]
